import { useState } from "react";

const TREE = [
  {
    name: "fraud_detection_system/",
    type: "root",
    desc: "Project Root",
    children: [
      { name: ".env", type: "config", desc: "SECRET_KEY, DEBUG, REDIS_URL, ALLOWED_HOSTS" },
      { name: ".gitignore", type: "config", desc: "Ignore venv, *.pyc, db.sqlite3, .env, ml/*.joblib" },
      { name: "requirements.txt", type: "config", desc: "Django, DRF, Channels, SHAP, sklearn, Redis, Daphne" },
      { name: "setup.py", type: "script", desc: "One-command install + migrate + train + launch" },
      { name: "README.md", type: "doc", desc: "Full API reference, architecture diagram, setup guide" },
      {
        name: "backend/",
        type: "folder",
        desc: "Django ASGI Application",
        children: [
          { name: "manage.py", type: "django", desc: "Django CLI entry point" },
          { name: "db.sqlite3", type: "db", desc: "SQLite database (auto-created on migrate)" },
          {
            name: "core/",
            type: "folder",
            desc: "Django Project Config Package",
            children: [
              { name: "__init__.py", type: "init", desc: "" },
              { name: "settings.py", type: "django", desc: "INSTALLED_APPS, Channels, CORS, DRF, Redis, ML path" },
              { name: "urls.py", type: "django", desc: "Root URL conf → /api/* + /admin/" },
              { name: "asgi.py", type: "django", desc: "Daphne ASGI: HTTP + WebSocket ProtocolTypeRouter" },
              { name: "wsgi.py", type: "django", desc: "WSGI fallback for non-WS deployments" },
            ],
          },
          {
            name: "fraud_app/",
            type: "folder",
            desc: "Main Django Application",
            children: [
              { name: "__init__.py", type: "init", desc: "" },
              { name: "apps.py", type: "django", desc: "AppConfig — FraudAppConfig" },
              { name: "admin.py", type: "django", desc: "Register Transaction, ChatMessage, AlertRule" },
              { name: "models.py", type: "model", desc: "Transaction | ChatMessage | AlertRule models + UUIDs" },
              { name: "serializers.py", type: "drf", desc: "TransactionInput/Result | Chat | Summary | AlertRule" },
              { name: "views.py", type: "view", desc: "6 REST APIViews: analyze, chat, transactions, stats, alerts, health" },
              { name: "urls.py", type: "django", desc: "REST URL patterns for all 6 endpoints" },
              { name: "consumers.py", type: "ws", desc: "AsyncWebsocketConsumer — analyze | chat | ping | alerts" },
              { name: "routing.py", type: "ws", desc: "WebSocket URL: ws/fraud/<session_id>/" },
              { name: "chat_engine.py", type: "ml", desc: "NLU parser + SHAP-aware response generation" },
              { name: "ml_service.py", type: "ml", desc: "FraudDetectionService singleton — RandomForest + SHAP" },
              {
                name: "ml/",
                type: "folder",
                desc: "Trained Model Artifacts (auto-generated)",
                children: [
                  { name: "fraud_model.joblib", type: "artifact", desc: "Trained RandomForest classifier (auto-saved on first run)" },
                  { name: "scaler.joblib", type: "artifact", desc: "StandardScaler fitted on training data" },
                ],
              },
              {
                name: "migrations/",
                type: "folder",
                desc: "Django DB Migrations",
                children: [
                  { name: "__init__.py", type: "init", desc: "" },
                  { name: "0001_initial.py", type: "migration", desc: "Creates Transaction, ChatMessage, AlertRule tables" },
                ],
              },
              {
                name: "tests/",
                type: "folder",
                desc: "Unit + Integration Tests",
                children: [
                  { name: "__init__.py", type: "init", desc: "" },
                  { name: "test_ml_service.py", type: "test", desc: "FraudDetectionService analyze() + SHAP output" },
                  { name: "test_views.py", type: "test", desc: "REST endpoint tests (analyze, chat, stats)" },
                  { name: "test_consumers.py", type: "test", desc: "WebSocket consumer protocol tests" },
                ],
              },
            ],
          },
          {
            name: "staticfiles/",
            type: "folder",
            desc: "Collected static assets (auto-generated by collectstatic)",
            children: [],
          },
        ],
      },
      {
        name: "frontend/",
        type: "folder",
        desc: "React + Vite Frontend",
        children: [
          { name: "package.json", type: "config", desc: "React 18, Vite, Recharts, TailwindCSS deps" },
          { name: "vite.config.js", type: "config", desc: "Proxy /api → localhost:8000, WS proxy" },
          { name: "tailwind.config.js", type: "config", desc: "Custom dark theme tokens" },
          { name: "index.html", type: "html", desc: "Vite entry HTML shell" },
          {
            name: "src/",
            type: "folder",
            desc: "React Source",
            children: [
              { name: "main.jsx", type: "react", desc: "ReactDOM.createRoot entry point" },
              { name: "App.jsx", type: "react", desc: "Root layout — tabs, header, alerts, stats" },
              {
                name: "components/",
                type: "folder",
                desc: "Reusable UI Components",
                children: [
                  { name: "ChatPane.jsx", type: "react", desc: "Message list + input + suggestions" },
                  { name: "ChatBubble.jsx", type: "react", desc: "User/assistant message with markdown bold" },
                  { name: "AnalysisCard.jsx", type: "react", desc: "Risk gauge + SHAP bars + verdict badges" },
                  { name: "RiskGauge.jsx", type: "react", desc: "SVG semicircle gauge with needle animation" },
                  { name: "SHAPBar.jsx", type: "react", desc: "Animated feature attribution bar chart" },
                  { name: "TransactionForm.jsx", type: "react", desc: "12-feature input form with toggles" },
                  { name: "WSStatusDot.jsx", type: "react", desc: "Live/Demo indicator dot with pulse" },
                  { name: "AlertBanner.jsx", type: "react", desc: "Floating critical/high alert toasts" },
                  { name: "StatPill.jsx", type: "react", desc: "Header stat pills (total, fraud, avg risk)" },
                ],
              },
              {
                name: "hooks/",
                type: "folder",
                desc: "Custom React Hooks",
                children: [
                  { name: "useWebSocket.js", type: "hook", desc: "WS connect/disconnect/send with reconnect logic" },
                  { name: "useFraudAPI.js", type: "hook", desc: "fetch() wrappers for REST endpoints" },
                  { name: "useSessionStats.js", type: "hook", desc: "Running totals: analyzed, fraud, avg score" },
                ],
              },
              {
                name: "api/",
                type: "folder",
                desc: "API Client Layer",
                children: [
                  { name: "client.js", type: "api", desc: "Base fetch with base URL, headers, error handling" },
                  { name: "fraud.js", type: "api", desc: "analyzeTransaction(), sendChat(), getStats()" },
                ],
              },
              {
                name: "constants/",
                type: "folder",
                desc: "Shared Constants",
                children: [
                  { name: "riskColors.js", type: "const", desc: "low/medium/high/critical color tokens" },
                  { name: "merchantCategories.js", type: "const", desc: "10 merchant category labels" },
                ],
              },
              {
                name: "styles/",
                type: "folder",
                desc: "CSS / Fonts",
                children: [
                  { name: "globals.css", type: "css", desc: "CSS variables, scrollbar, keyframe animations" },
                ],
              },
            ],
          },
          {
            name: "public/",
            type: "folder",
            desc: "Static Public Assets",
            children: [
              { name: "favicon.ico", type: "asset", desc: "Lock icon favicon" },
            ],
          },
        ],
      },
      {
        name: "nginx/",
        type: "folder",
        desc: "Production Reverse Proxy Config",
        children: [
          { name: "nginx.conf", type: "config", desc: "Proxy HTTP → Daphne:8000, WS upgrade headers" },
        ],
      },
      {
        name: "docker/",
        type: "folder",
        desc: "Container Setup",
        children: [
          { name: "Dockerfile", type: "docker", desc: "Python 3.11 slim, installs deps, runs Daphne" },
          { name: "docker-compose.yml", type: "docker", desc: "web + redis + nginx services" },
          { name: ".dockerignore", type: "config", desc: "Excludes venv, __pycache__, *.joblib" },
        ],
      },
    ],
  },
];

const TYPE_META = {
  root:      { icon: "🗂️",  color: "#00e5ff", bg: "#00e5ff15" },
  folder:    { icon: "📁",  color: "#ffb800", bg: "#ffb80015" },
  django:    { icon: "🐍",  color: "#44b883", bg: "#44b88315" },
  model:     { icon: "🗃️",  color: "#a78bfa", bg: "#a78bfa15" },
  drf:       { icon: "🔧",  color: "#60a5fa", bg: "#60a5fa15" },
  view:      { icon: "👁️",  color: "#34d399", bg: "#34d39915" },
  ws:        { icon: "⚡",  color: "#fbbf24", bg: "#fbbf2415" },
  ml:        { icon: "🧠",  color: "#f472b6", bg: "#f472b615" },
  react:     { icon: "⚛️",  color: "#61dafb", bg: "#61dafb15" },
  hook:      { icon: "🪝",  color: "#a3e635", bg: "#a3e63515" },
  api:       { icon: "🌐",  color: "#38bdf8", bg: "#38bdf815" },
  config:    { icon: "⚙️",  color: "#94a3b8", bg: "#94a3b815" },
  script:    { icon: "▶️",  color: "#00ff88", bg: "#00ff8815" },
  doc:       { icon: "📄",  color: "#e2e8f0", bg: "#e2e8f015" },
  migration: { icon: "🔄",  color: "#fb923c", bg: "#fb923c15" },
  test:      { icon: "✅",  color: "#4ade80", bg: "#4ade8015" },
  artifact:  { icon: "💾",  color: "#c084fc", bg: "#c084fc15" },
  docker:    { icon: "🐳",  color: "#38bdf8", bg: "#38bdf815" },
  init:      { icon: "·",   color: "#334155", bg: "transparent" },
  db:        { icon: "🗄️",  color: "#f87171", bg: "#f8717115" },
  html:      { icon: "🌐",  color: "#fb923c", bg: "#fb923c15" },
  css:       { icon: "🎨",  color: "#a78bfa", bg: "#a78bfa15" },
  const:     { icon: "📌",  color: "#94a3b8", bg: "#94a3b815" },
  asset:     { icon: "🖼️",  color: "#94a3b8", bg: "#94a3b815" },
};

const API_ENDPOINTS = [
  { method: "POST", path: "/api/analyze/",           color: "#00ff88", desc: "Run ML fraud analysis + SHAP" },
  { method: "POST", path: "/api/chat/",              color: "#00ff88", desc: "Send chat message" },
  { method: "GET",  path: "/api/chat/?session_id=",  color: "#60a5fa", desc: "Get conversation history" },
  { method: "GET",  path: "/api/transactions/",      color: "#60a5fa", desc: "List transactions" },
  { method: "GET",  path: "/api/transactions/<id>/", color: "#60a5fa", desc: "Transaction detail" },
  { method: "GET",  path: "/api/stats/",             color: "#60a5fa", desc: "Dashboard stats" },
  { method: "GET",  path: "/api/alerts/",            color: "#60a5fa", desc: "List alert rules" },
  { method: "POST", path: "/api/alerts/",            color: "#00ff88", desc: "Create alert rule" },
  { method: "GET",  path: "/api/health/",            color: "#60a5fa", desc: "Service health check" },
  { method: "WS",   path: "ws/fraud/<session_id>/",  color: "#fbbf24", desc: "Real-time analysis stream" },
];

function TreeNode({ node, depth = 0 }) {
  const [open, setOpen] = useState(depth < 2);
  const meta = TYPE_META[node.type] || TYPE_META.config;
  const hasChildren = node.children && node.children.length > 0;
  const isFolder = node.type === "folder" || node.type === "root";

  return (
    <div style={{ marginLeft: depth === 0 ? 0 : 20 }}>
      <div
        onClick={() => hasChildren && setOpen(o => !o)}
        style={{
          display: "flex", alignItems: "center", gap: 8,
          padding: "4px 8px", borderRadius: 6, cursor: hasChildren ? "pointer" : "default",
          marginBottom: 2, transition: "background 0.15s",
          background: "transparent",
          userSelect: "none",
        }}
        onMouseEnter={e => e.currentTarget.style.background = "#ffffff08"}
        onMouseLeave={e => e.currentTarget.style.background = "transparent"}
      >
        {/* Tree line */}
        {depth > 0 && (
          <span style={{ color: "#1e3a5f", fontSize: 12, fontFamily: "Space Mono", flexShrink: 0 }}>
            {hasChildren ? (open ? "▼" : "▶") : "├─"}
          </span>
        )}

        {/* Icon + badge */}
        <span style={{
          fontSize: node.type === "init" ? 18 : 15,
          flexShrink: 0, lineHeight: 1,
        }}>
          {isFolder && !open && hasChildren ? "📂" : meta.icon}
        </span>

        {/* Name */}
        <span style={{
          fontFamily: "Space Mono", fontSize: 12.5,
          color: meta.color, fontWeight: isFolder ? 700 : 400,
          flexShrink: 0,
        }}>
          {node.name}
        </span>

        {/* Type badge */}
        {node.type !== "init" && node.type !== "root" && (
          <span style={{
            fontSize: 9, padding: "1px 6px", borderRadius: 10,
            background: meta.bg, color: meta.color,
            fontFamily: "Space Mono", letterSpacing: 1,
            border: `1px solid ${meta.color}33`,
            flexShrink: 0,
          }}>
            {node.type.toUpperCase()}
          </span>
        )}

        {/* Description */}
        {node.desc && (
          <span style={{
            fontFamily: "Syne", fontSize: 11.5, color: "#4a6580",
            overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap",
          }}>
            — {node.desc}
          </span>
        )}
      </div>

      {/* Children */}
      {hasChildren && open && (
        <div style={{
          borderLeft: depth === 0 ? "none" : "1px solid #1a2d45",
          marginLeft: 12, paddingLeft: 4,
        }}>
          {node.children.map((child, i) => (
            <TreeNode key={i} node={child} depth={depth + 1} />
          ))}
        </div>
      )}
    </div>
  );
}

export default function App() {
  const [tab, setTab] = useState("tree");

  const totalFiles = (node) => {
    if (!node.children) return 1;
    return node.children.reduce((s, c) => s + totalFiles(c), 0);
  };

  return (
    <div style={{
      minHeight: "100vh", background: "#080c10",
      color: "#c8daf0", fontFamily: "Syne, sans-serif",
      padding: 0,
    }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Syne:wght@400;600;700;800&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        ::-webkit-scrollbar { width: 4px; }
        ::-webkit-scrollbar-track { background: #080c10; }
        ::-webkit-scrollbar-thumb { background: #1a2d45; border-radius: 2px; }
        body { background: #080c10; }
      `}</style>

      {/* Header */}
      <div style={{
        padding: "16px 24px", borderBottom: "1px solid #1a2d45",
        background: "#0d1420", display: "flex", alignItems: "center", justifyContent: "space-between",
      }}>
        <div>
          <div style={{ fontFamily: "Space Mono", fontSize: 18, fontWeight: 700, color: "#00e5ff", letterSpacing: 1 }}>
            🔒 FraudShield XAI
          </div>
          <div style={{ fontFamily: "Space Mono", fontSize: 10, color: "#4a6580", letterSpacing: 3, marginTop: 3 }}>
            FULL PROJECT STRUCTURE
          </div>
        </div>
        <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
          {[
            ["~50", "FILES", "#00e5ff"],
            ["14", "DELIVERED", "#00ff88"],
            ["6", "REST APIs", "#ffb800"],
            ["1", "WebSocket", "#fbbf24"],
          ].map(([v, l, c]) => (
            <div key={l} style={{
              padding: "6px 12px", background: `${c}11`,
              border: `1px solid ${c}33`, borderRadius: 7,
              textAlign: "center",
            }}>
              <div style={{ fontFamily: "Space Mono", fontSize: 16, fontWeight: 700, color: c }}>{v}</div>
              <div style={{ fontFamily: "Space Mono", fontSize: 8, color: "#4a6580", letterSpacing: 2 }}>{l}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Tabs */}
      <div style={{ display: "flex", borderBottom: "1px solid #1a2d45", background: "#080c10" }}>
        {[["tree","📁 Folder Tree"], ["api","🌐 API Endpoints"], ["flow","🔄 Data Flow"]].map(([id, label]) => (
          <button key={id} onClick={() => setTab(id)} style={{
            padding: "10px 20px", background: "none", border: "none",
            borderBottom: tab === id ? "2px solid #00e5ff" : "2px solid transparent",
            color: tab === id ? "#00e5ff" : "#4a6580",
            fontFamily: "Syne", fontSize: 13, fontWeight: 600, cursor: "pointer",
          }}>{label}</button>
        ))}
      </div>

      {/* Content */}
      <div style={{ padding: "20px 24px", maxWidth: 1000 }}>

        {tab === "tree" && (
          <div>
            <div style={{ fontFamily: "Space Mono", fontSize: 10, color: "#4a6580", letterSpacing: 3, marginBottom: 16 }}>
              CLICK FOLDERS TO EXPAND / COLLAPSE
            </div>

            {/* Legend */}
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 20 }}>
              {[["django","Django"],["ml","ML/AI"],["ws","WebSocket"],["react","React"],["drf","DRF"],["test","Tests"],["docker","Docker"]].map(([type, label]) => {
                const m = TYPE_META[type];
                return (
                  <span key={type} style={{
                    padding: "3px 9px", borderRadius: 10,
                    background: m.bg, color: m.color,
                    fontFamily: "Space Mono", fontSize: 9, letterSpacing: 1,
                    border: `1px solid ${m.color}33`,
                  }}>{m.icon} {label}</span>
                );
              })}
            </div>

            <div style={{ background: "#0d1420", border: "1px solid #1a2d45", borderRadius: 10, padding: "16px 12px" }}>
              {TREE.map((node, i) => <TreeNode key={i} node={node} depth={0} />)}
            </div>
          </div>
        )}

        {tab === "api" && (
          <div>
            <div style={{ fontFamily: "Space Mono", fontSize: 10, color: "#4a6580", letterSpacing: 3, marginBottom: 20 }}>
              BASE URL: http://localhost:8000
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
              {API_ENDPOINTS.map((ep, i) => (
                <div key={i} style={{
                  display: "flex", alignItems: "center", gap: 12,
                  background: "#0d1420", border: "1px solid #1a2d45",
                  borderLeft: `3px solid ${ep.color}`,
                  borderRadius: 8, padding: "12px 16px",
                }}>
                  <span style={{
                    fontFamily: "Space Mono", fontSize: 10, fontWeight: 700,
                    color: ep.color, background: `${ep.color}22`,
                    padding: "3px 8px", borderRadius: 5, minWidth: 44, textAlign: "center",
                    border: `1px solid ${ep.color}44`,
                  }}>{ep.method}</span>
                  <code style={{ fontFamily: "Space Mono", fontSize: 12.5, color: "#c8daf0", flex: 1 }}>
                    {ep.path}
                  </code>
                  <span style={{ fontFamily: "Syne", fontSize: 12, color: "#4a6580" }}>{ep.desc}</span>
                </div>
              ))}
            </div>

            {/* WebSocket protocol */}
            <div style={{ marginTop: 24, background: "#0d1420", border: "1px solid #fbbf2444", borderRadius: 10, padding: 16 }}>
              <div style={{ fontFamily: "Space Mono", fontSize: 9, color: "#fbbf24", letterSpacing: 3, marginBottom: 12 }}>
                ⚡ WEBSOCKET PROTOCOL — ws://localhost:8000/ws/fraud/{"<session_id>"}/
              </div>
              {[
                ["CLIENT → SERVER", [
                  ['{ "type": "analyze", "transaction": {...} }', "Send transaction for ML analysis"],
                  ['{ "type": "chat",    "message": "..." }',    "Send chat message"],
                  ['{ "type": "ping" }',                         "Heartbeat"],
                ]],
                ["SERVER → CLIENT", [
                  ['{ "type": "analysis_result", "data": {...} }', "Full ML result + SHAP values"],
                  ['{ "type": "chat_response",   "message": "..." }', "Assistant reply"],
                  ['{ "type": "alert",  "level": "critical" }',  "Pushed fraud alert"],
                  ['{ "type": "pong" }',                          "Heartbeat response"],
                ]],
              ].map(([dir, msgs]) => (
                <div key={dir} style={{ marginBottom: 14 }}>
                  <div style={{ fontFamily: "Space Mono", fontSize: 9, color: "#4a6580", letterSpacing: 2, marginBottom: 8 }}>{dir}</div>
                  {msgs.map(([payload, desc], i) => (
                    <div key={i} style={{ display: "flex", gap: 12, marginBottom: 6, alignItems: "flex-start" }}>
                      <code style={{ fontFamily: "Space Mono", fontSize: 11, color: "#fbbf24", flex: 1 }}>{payload}</code>
                      <span style={{ fontFamily: "Syne", fontSize: 11, color: "#4a6580", minWidth: 180 }}>{desc}</span>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </div>
        )}

        {tab === "flow" && (
          <div style={{ fontFamily: "Space Mono", fontSize: 12 }}>
            <div style={{ fontFamily: "Space Mono", fontSize: 10, color: "#4a6580", letterSpacing: 3, marginBottom: 20 }}>
              DATA FLOW — REQUEST LIFECYCLE
            </div>
            {[
              {
                step: "01", title: "User Input", color: "#00e5ff",
                desc: "React frontend collects 12 transaction features via form or chat NLU parser",
                detail: "chat_engine.py extracts amount, hour, is_international, velocity etc. from natural language",
              },
              {
                step: "02", title: "Transport", color: "#60a5fa",
                desc: "POST /api/analyze/ (REST) or WS message type='analyze' (real-time)",
                detail: "TransactionInputSerializer validates all 12 fields, applies min/max constraints",
              },
              {
                step: "03", title: "ML Analysis", color: "#f472b6",
                desc: "FraudDetectionService.analyze() — singleton loaded once on startup",
                detail: "StandardScaler → RandomForest.predict_proba() → fraud probability [0,1]",
              },
              {
                step: "04", title: "SHAP Explanation", color: "#a78bfa",
                desc: "TreeExplainer generates per-feature SHAP values for the fraud class",
                detail: "12 features sorted by |SHAP| — direction (increases/decreases risk) + magnitude",
              },
              {
                step: "05", title: "Response Build", color: "#34d399",
                desc: "Risk level (low/medium/high/critical), explanation text, top factors assembled",
                detail: "_build_explanation() generates human-readable summary with emoji risk indicators",
              },
              {
                step: "06", title: "Persist + Alert", color: "#fbbf24",
                desc: "Transaction saved to DB. If high/critical: channel_layer.group_send() broadcasts alert",
                detail: "All connected WS clients in session group receive type='alert' push notification",
              },
              {
                step: "07", title: "Frontend Render", color: "#00ff88",
                desc: "Risk gauge, SHAP bars, confidence badges rendered with animation",
                detail: "Animated SVG gauge needle, CSS bar-fill animation, colour-coded by risk level",
              },
            ].map((s, i) => (
              <div key={i} style={{
                display: "flex", gap: 16, marginBottom: 12,
                background: "#0d1420", border: `1px solid ${s.color}33`,
                borderLeft: `3px solid ${s.color}`,
                borderRadius: 8, padding: "12px 16px",
              }}>
                <div style={{
                  fontFamily: "Space Mono", fontSize: 20, fontWeight: 700,
                  color: s.color, opacity: 0.3, minWidth: 36,
                }}>{s.step}</div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontFamily: "Syne", fontWeight: 700, fontSize: 14, color: s.color, marginBottom: 4 }}>{s.title}</div>
                  <div style={{ fontFamily: "Syne", fontSize: 13, color: "#c8daf0", marginBottom: 4 }}>{s.desc}</div>
                  <div style={{ fontFamily: "Space Mono", fontSize: 10, color: "#4a6580" }}>{s.detail}</div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
